### Basic Imports and Transformations

In [1]:
import torch

In [2]:
dd = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [3]:
t = torch.tensor(dd)

In [4]:
t.shape

torch.Size([3, 3])

**Reshaping Tensors**

Note: Product of component values must = total number of tensor elements

In [13]:
# 3x3 Tensor reshaped to 1x9. 3*3 = 1*9 == Good!
t.reshape(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [11]:
t.reshape(1,9).shape

torch.Size([1, 9])

CNN Tensor Shape

(1,4): [B, C, H, W]
* B = Batch Size
* C = Color Channels (ex: 3 for RGB; 1 for grayscale)
* H = Image Height
* W = Image Width

Example:

[3, 1, 28, 28] = 3 Batches of a grayscale image, 28 height x 28 width

### Data Preprocessing

In [16]:
import torch
import numpy as np

In [17]:
t = torch.Tensor()

In [18]:
type(t)

torch.Tensor

Datatypes, Device, Layout

In [21]:
print(t.dtype)
print(t.device)
print(t.layout) # how tensor is laid out in memory. strided by default.

torch.float32
cpu
torch.strided


Create Tensors from Data

In [37]:
data = np.array([1,2,3])

In [38]:
torch.tensor(data)

tensor([1, 2, 3], dtype=torch.int32)

In [39]:
torch.from_numpy(data)

tensor([1, 2, 3], dtype=torch.int32)

In [40]:
torch.as_tensor(data)

tensor([1, 2, 3], dtype=torch.int32)

In [42]:
torch.Tensor(data) # Class constructor modifies dtype

tensor([1., 2., 3.])

### Creation without Data

[Identity Matrix](https://en.wikipedia.org/wiki/Identity_matrix):

In [44]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [45]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [46]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [48]:
torch.rand(4,2)

tensor([[0.0302, 0.4055],
        [0.5734, 0.7371],
        [0.2796, 0.0771],
        [0.2441, 0.7957]])