### Basic Imports and Transformations

In [1]:
import torch

In [2]:
dd = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [3]:
t = torch.tensor(dd)

In [4]:
t.shape

torch.Size([3, 3])

**Reshaping Tensors**

Note: Product of component values must = total number of tensor elements

In [13]:
# 3x3 Tensor reshaped to 1x9. 3*3 = 1*9 == Good!
t.reshape(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [11]:
t.reshape(1,9).shape

torch.Size([1, 9])

CNN Tensor Shape

(1,4): [B, C, H, W]
* B = Batch Size
* C = Color Channels (ex: 3 for RGB; 1 for grayscale)
* H = Image Height
* W = Image Width

Example:

[3, 1, 28, 28] = 3 Batches of a grayscale image, 28 height x 28 width

### Data Preprocessing

In [16]:
import torch
import numpy as np

In [17]:
t = torch.Tensor()

In [18]:
type(t)

torch.Tensor

Datatypes, Device, Layout

In [21]:
print(t.dtype)
print(t.device)
print(t.layout) # how tensor is laid out in memory. strided by default.

torch.float32
cpu
torch.strided


Create Tensors from Data

In [37]:
data = np.array([1,2,3])

In [38]:
torch.tensor(data)

tensor([1, 2, 3], dtype=torch.int32)

In [39]:
torch.from_numpy(data)

tensor([1, 2, 3], dtype=torch.int32)

In [40]:
torch.as_tensor(data)

tensor([1, 2, 3], dtype=torch.int32)

In [42]:
torch.Tensor(data) # Class constructor modifies dtype

tensor([1., 2., 3.])

### Creation without Data

[Identity Matrix](https://en.wikipedia.org/wiki/Identity_matrix):

In [44]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [45]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [46]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [48]:
torch.rand(4,2)

tensor([[0.0302, 0.4055],
        [0.5734, 0.7371],
        [0.2796, 0.0771],
        [0.2441, 0.7957]])

### PyTorch Tensor Creation - Best Options

For factory functions, dtype is inferred by the incoming data.

**Copy Data**
* `torch.Tensor` and `torch.tensor` make a copy in memory. 
    * Changing the original data values will ***not*** affect the tensor.
    
**Share Data**    
* `torch.as_tensor` and `torch.from_numpy`share memory location. 
    * Changing the original data values ***changes*** the tensor.

In [49]:
data = np.array([x for x in range(1,4)])

In [51]:
t1 = torch.Tensor(data) # Uses class constructor
t2 = torch.tensor(data) # Factory function. https://en.wikipedia.org/wiki/Factory_(object-oriented_programming)
t3 = torch.as_tensor(data) # Factory function
t4 = torch.from_numpy(data) # Factory function

In [52]:
torch.get_default_dtype() # Explains dtype designation in t1

torch.float32

## Tensor Operation Types
1. Reshaping
2. Element-wise
3. Reduction
4. Access

In [53]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [54]:
t.shape

torch.Size([3, 4])

In [57]:
t.size()

torch.Size([3, 4])

In [59]:
len(t.shape) # Shows tensor's rank

2

Display Tensor's Number of Elements

In [63]:
torch.tensor(t.shape).prod() # convert the shape to a tensor, ask for product

tensor(12)

In [62]:
t.numel() # yields NUMber of ELements

12

**Possible Reshapes for a 3x4 Tensor WITHOUT changing rank**

*Hint: Combinations will be factors of numel (12)*

In [64]:
t.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [65]:
t.reshape(2,6)

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [66]:
t.reshape(3,4)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [67]:
t.reshape(4,3)

tensor([[1., 1., 1.],
        [1., 2., 2.],
        [2., 2., 3.],
        [3., 3., 3.]])

In [68]:
t.reshape(6,2)

tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]])

In [69]:
t.reshape(12,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

**Reshape, Changing Rank:**

In [70]:
t.reshape(2,2,3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

* Squeezing a Tensor removes all axes with a length of 1
* Unsqueezing a Tensor adds a dimension with a length of 1

Allows us to expand or shrink the rank of our tensor

### squeeze() and unsqueeze()

Original:

In [74]:
print(t.reshape(1,12))
print(t.reshape(1,12).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


squeeze() removes the first axis:

In [76]:
print(t.reshape(1,12).squeeze()) # Squeeze to remove all axes with rank 1
print(t.reshape(1,12).squeeze().shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


unsqueeze() adds back an axis of 1 at the beginning:

In [77]:
print(t.reshape(1,12).squeeze().unsqueeze(dim=0))
print(t.reshape(1,12).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


Flatten is used to transition between convolutional layers to a fully-connected layer

In [81]:
def flatten(t):
    '''Takes a tensor t and flattens to size (1, n) where n = t.numel()'''
    t = t.reshape(1, -1)
    t = t.squeeze()
    return t

In [85]:
t

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [86]:
flatten(t)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

**Concatenate Tensors**

In [88]:
t1 = torch.tensor([
    [1,2],
    [3,4]
])

t2 = torch.tensor([
    [5,6],
    [7,8]
])

In [89]:
torch.cat((t1, t2), dim=0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [90]:
torch.cat((t1,t2),dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])